// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pb/state.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Cell int32

const (
	Cell_EMPTY  Cell = 0
	Cell_SHIP   Cell = 1
	Cell_MISSED Cell = 2
	Cell_GOT    Cell = 3
)

// Enum value maps for Cell.
var (
	Cell_name = map[int32]string{
		0: "EMPTY",
		1: "SHIP",
		2: "MISSED",
		3: "GOT",
	}
	Cell_value = map[string]int32{
		"EMPTY":  0,
		"SHIP":   1,
		"MISSED": 2,
		"GOT":    3,
	}
)

func (x Cell) Enum() *Cell {
	p := new(Cell)
	*p = x
	return p
}

func (x Cell) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cell) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_state_proto_enumTypes[0].Descriptor()
}

func (Cell) Type() protoreflect.EnumType {
	return &file_pb_state_proto_enumTypes[0]
}

func (x Cell) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cell.Descriptor instead.
func (Cell) EnumDescriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 []Cell `protobuf:"varint,1,rep,packed,name=Field1,proto3,enum=Cell" json:"Field1,omitempty"`
	Field2 []Cell `protobuf:"varint,2,rep,packed,name=Field2,proto3,enum=Cell" json:"Field2,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetField1() []Cell {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *State) GetField2() []Cell {
	if x != nil {
		return x.Field2
	}
	return nil
}

var File_pb_state_proto protoreflect.FileDescriptor

var file_pb_state_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x45, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x06, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43, 0x65, 0x6c, 0x6c,
	0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x1d, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x32, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x2a, 0x30, 0x0a, 0x04, 0x43, 0x65, 0x6c, 0x6c, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48,
	0x49, 0x50, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x49, 0x53, 0x53, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x47, 0x4f, 0x54, 0x10, 0x03, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_state_proto_rawDescOnce sync.Once
	file_pb_state_proto_rawDescData = file_pb_state_proto_rawDesc
)

func file_pb_state_proto_rawDescGZIP() []byte {
	file_pb_state_proto_rawDescOnce.Do(func() {
		file_pb_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_state_proto_rawDescData)
	})
	return file_pb_state_proto_rawDescData
}

var file_pb_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_state_proto_goTypes = []interface{}{
	(Cell)(0),     // 0: Cell
	(*State)(nil), // 1: State
}
var file_pb_state_proto_depIdxs = []int32{
	0, // 0: State.Field1:type_name -> Cell
	0, // 1: State.Field2:type_name -> Cell
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_state_proto_init() }
func file_pb_state_proto_init() {
	if File_pb_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_state_proto_goTypes,
		DependencyIndexes: file_pb_state_proto_depIdxs,
		EnumInfos:         file_pb_state_proto_enumTypes,
		MessageInfos:      file_pb_state_proto_msgTypes,
	}.Build()
	File_pb_state_proto = out.File
	file_pb_state_proto_rawDesc = nil
	file_pb_state_proto_goTypes = nil
	file_pb_state_proto_depIdxs = nil
}
