// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pb/state.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Cell int32

const (
	Cell_EMPTY  Cell = 0
	Cell_SHIP   Cell = 1
	Cell_MISSED Cell = 2
	Cell_GOT    Cell = 3
)

// Enum value maps for Cell.
var (
	Cell_name = map[int32]string{
		0: "EMPTY",
		1: "SHIP",
		2: "MISSED",
		3: "GOT",
	}
	Cell_value = map[string]int32{
		"EMPTY":  0,
		"SHIP":   1,
		"MISSED": 2,
		"GOT":    3,
	}
)

func (x Cell) Enum() *Cell {
	p := new(Cell)
	*p = x
	return p
}

func (x Cell) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cell) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_state_proto_enumTypes[0].Descriptor()
}

func (Cell) Type() protoreflect.EnumType {
	return &file_pb_state_proto_enumTypes[0]
}

func (x Cell) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cell.Descriptor instead.
func (Cell) EnumDescriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 []Cell `protobuf:"varint,1,rep,packed,name=field1,proto3,enum=Cell" json:"field1,omitempty"`
	Field2 []Cell `protobuf:"varint,2,rep,packed,name=field2,proto3,enum=Cell" json:"field2,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetField1() []Cell {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *State) GetField2() []Cell {
	if x != nil {
		return x.Field2
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Action_Skip
	//	*Action_Setup
	//	*Action_Fire
	Data isAction_Data `protobuf_oneof:"data"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{1}
}

func (m *Action) GetData() isAction_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Action) GetSkip() *ActionSkip {
	if x, ok := x.GetData().(*Action_Skip); ok {
		return x.Skip
	}
	return nil
}

func (x *Action) GetSetup() *ActionSetup {
	if x, ok := x.GetData().(*Action_Setup); ok {
		return x.Setup
	}
	return nil
}

func (x *Action) GetFire() *ActionFire {
	if x, ok := x.GetData().(*Action_Fire); ok {
		return x.Fire
	}
	return nil
}

type isAction_Data interface {
	isAction_Data()
}

type Action_Skip struct {
	Skip *ActionSkip `protobuf:"bytes,1,opt,name=skip,proto3,oneof"`
}

type Action_Setup struct {
	Setup *ActionSetup `protobuf:"bytes,2,opt,name=setup,proto3,oneof"`
}

type Action_Fire struct {
	Fire *ActionFire `protobuf:"bytes,3,opt,name=fire,proto3,oneof"`
}

func (*Action_Skip) isAction_Data() {}

func (*Action_Setup) isAction_Data() {}

func (*Action_Fire) isAction_Data() {}

type ActionSkip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActionSkip) Reset() {
	*x = ActionSkip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionSkip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSkip) ProtoMessage() {}

func (x *ActionSkip) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSkip.ProtoReflect.Descriptor instead.
func (*ActionSkip) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{2}
}

type ActionSetup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipL4N1 *ActionSetup_Ship `protobuf:"bytes,1,opt,name=shipL4N1,proto3" json:"shipL4N1,omitempty"`
	ShipL3N1 *ActionSetup_Ship `protobuf:"bytes,2,opt,name=shipL3N1,proto3" json:"shipL3N1,omitempty"`
	ShipL3N2 *ActionSetup_Ship `protobuf:"bytes,3,opt,name=shipL3N2,proto3" json:"shipL3N2,omitempty"`
	ShipL2N1 *ActionSetup_Ship `protobuf:"bytes,4,opt,name=shipL2N1,proto3" json:"shipL2N1,omitempty"`
	ShipL2N2 *ActionSetup_Ship `protobuf:"bytes,5,opt,name=shipL2N2,proto3" json:"shipL2N2,omitempty"`
	ShipL2N3 *ActionSetup_Ship `protobuf:"bytes,6,opt,name=shipL2N3,proto3" json:"shipL2N3,omitempty"`
	ShipL1N1 *ActionSetup_Ship `protobuf:"bytes,7,opt,name=shipL1N1,proto3" json:"shipL1N1,omitempty"`
	ShipL1N2 *ActionSetup_Ship `protobuf:"bytes,8,opt,name=shipL1N2,proto3" json:"shipL1N2,omitempty"`
	ShipL1N3 *ActionSetup_Ship `protobuf:"bytes,9,opt,name=shipL1N3,proto3" json:"shipL1N3,omitempty"`
	ShipL1N4 *ActionSetup_Ship `protobuf:"bytes,10,opt,name=shipL1N4,proto3" json:"shipL1N4,omitempty"`
}

func (x *ActionSetup) Reset() {
	*x = ActionSetup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSetup) ProtoMessage() {}

func (x *ActionSetup) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSetup.ProtoReflect.Descriptor instead.
func (*ActionSetup) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{3}
}

func (x *ActionSetup) GetShipL4N1() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL4N1
	}
	return nil
}

func (x *ActionSetup) GetShipL3N1() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL3N1
	}
	return nil
}

func (x *ActionSetup) GetShipL3N2() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL3N2
	}
	return nil
}

func (x *ActionSetup) GetShipL2N1() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL2N1
	}
	return nil
}

func (x *ActionSetup) GetShipL2N2() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL2N2
	}
	return nil
}

func (x *ActionSetup) GetShipL2N3() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL2N3
	}
	return nil
}

func (x *ActionSetup) GetShipL1N1() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL1N1
	}
	return nil
}

func (x *ActionSetup) GetShipL1N2() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL1N2
	}
	return nil
}

func (x *ActionSetup) GetShipL1N3() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL1N3
	}
	return nil
}

func (x *ActionSetup) GetShipL1N4() *ActionSetup_Ship {
	if x != nil {
		return x.ShipL1N4
	}
	return nil
}

type ActionFire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinate string `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
}

func (x *ActionFire) Reset() {
	*x = ActionFire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionFire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionFire) ProtoMessage() {}

func (x *ActionFire) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionFire.ProtoReflect.Descriptor instead.
func (*ActionFire) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{4}
}

func (x *ActionFire) GetCoordinate() string {
	if x != nil {
		return x.Coordinate
	}
	return ""
}

type ActionSetup_Ship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinate string `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Vertical   bool   `protobuf:"varint,2,opt,name=vertical,proto3" json:"vertical,omitempty"`
}

func (x *ActionSetup_Ship) Reset() {
	*x = ActionSetup_Ship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_state_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionSetup_Ship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSetup_Ship) ProtoMessage() {}

func (x *ActionSetup_Ship) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSetup_Ship.ProtoReflect.Descriptor instead.
func (*ActionSetup_Ship) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ActionSetup_Ship) GetCoordinate() string {
	if x != nil {
		return x.Coordinate
	}
	return ""
}

func (x *ActionSetup_Ship) GetVertical() bool {
	if x != nil {
		return x.Vertical
	}
	return false
}

var File_pb_state_proto protoreflect.FileDescriptor

var file_pb_state_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x45, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43, 0x65, 0x6c, 0x6c,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x1d, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x32, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x22, 0x7c, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x21, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6b, 0x69, 0x70, 0x48, 0x00, 0x52, 0x04,
	0x73, 0x6b, 0x69, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x48, 0x00, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x66, 0x69,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x46, 0x69, 0x72, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x72, 0x65, 0x42, 0x06, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x6b, 0x69, 0x70, 0x22, 0xa7, 0x04, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x34, 0x4e, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x34,
	0x4e, 0x31, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x33, 0x4e, 0x31, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x33, 0x4e,
	0x31, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x33, 0x4e, 0x32, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x33, 0x4e, 0x32,
	0x12, 0x2d, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x32, 0x4e, 0x31, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x2e, 0x53, 0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x32, 0x4e, 0x31, 0x12,
	0x2d, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x32, 0x4e, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x2e,
	0x53, 0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x32, 0x4e, 0x32, 0x12, 0x2d,
	0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x32, 0x4e, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x53,
	0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x32, 0x4e, 0x33, 0x12, 0x2d, 0x0a,
	0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x53, 0x68,
	0x69, 0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x31, 0x12, 0x2d, 0x0a, 0x08,
	0x73, 0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x53, 0x68, 0x69,
	0x70, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x32, 0x12, 0x2d, 0x0a, 0x08, 0x73,
	0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x33, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x53, 0x68, 0x69, 0x70,
	0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x33, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x68,
	0x69, 0x70, 0x4c, 0x31, 0x4e, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x52,
	0x08, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x31, 0x4e, 0x34, 0x1a, 0x42, 0x0a, 0x04, 0x53, 0x68, 0x69,
	0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x2c, 0x0a,
	0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x2a, 0x30, 0x0a, 0x04, 0x43,
	0x65, 0x6c, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x48, 0x49, 0x50, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x49, 0x53, 0x53,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x4f, 0x54, 0x10, 0x03, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_state_proto_rawDescOnce sync.Once
	file_pb_state_proto_rawDescData = file_pb_state_proto_rawDesc
)

func file_pb_state_proto_rawDescGZIP() []byte {
	file_pb_state_proto_rawDescOnce.Do(func() {
		file_pb_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_state_proto_rawDescData)
	})
	return file_pb_state_proto_rawDescData
}

var file_pb_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_state_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_state_proto_goTypes = []interface{}{
	(Cell)(0),                // 0: Cell
	(*State)(nil),            // 1: State
	(*Action)(nil),           // 2: Action
	(*ActionSkip)(nil),       // 3: ActionSkip
	(*ActionSetup)(nil),      // 4: ActionSetup
	(*ActionFire)(nil),       // 5: ActionFire
	(*ActionSetup_Ship)(nil), // 6: ActionSetup.Ship
}
var file_pb_state_proto_depIdxs = []int32{
	0,  // 0: State.field1:type_name -> Cell
	0,  // 1: State.field2:type_name -> Cell
	3,  // 2: Action.skip:type_name -> ActionSkip
	4,  // 3: Action.setup:type_name -> ActionSetup
	5,  // 4: Action.fire:type_name -> ActionFire
	6,  // 5: ActionSetup.shipL4N1:type_name -> ActionSetup.Ship
	6,  // 6: ActionSetup.shipL3N1:type_name -> ActionSetup.Ship
	6,  // 7: ActionSetup.shipL3N2:type_name -> ActionSetup.Ship
	6,  // 8: ActionSetup.shipL2N1:type_name -> ActionSetup.Ship
	6,  // 9: ActionSetup.shipL2N2:type_name -> ActionSetup.Ship
	6,  // 10: ActionSetup.shipL2N3:type_name -> ActionSetup.Ship
	6,  // 11: ActionSetup.shipL1N1:type_name -> ActionSetup.Ship
	6,  // 12: ActionSetup.shipL1N2:type_name -> ActionSetup.Ship
	6,  // 13: ActionSetup.shipL1N3:type_name -> ActionSetup.Ship
	6,  // 14: ActionSetup.shipL1N4:type_name -> ActionSetup.Ship
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pb_state_proto_init() }
func file_pb_state_proto_init() {
	if File_pb_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionSkip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionSetup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionFire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_state_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionSetup_Ship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_state_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Action_Skip)(nil),
		(*Action_Setup)(nil),
		(*Action_Fire)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_state_proto_goTypes,
		DependencyIndexes: file_pb_state_proto_depIdxs,
		EnumInfos:         file_pb_state_proto_enumTypes,
		MessageInfos:      file_pb_state_proto_msgTypes,
	}.Build()
	File_pb_state_proto = out.File
	file_pb_state_proto_rawDesc = nil
	file_pb_state_proto_goTypes = nil
	file_pb_state_proto_depIdxs = nil
}
